title: Claire's Personal Website
description: Resume and Image
theme: just-the-docs

url: https://claire-25.github.io/website/
aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
